name: Build And Deploy Docs
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
env:
  TZ: Asia/Shanghai
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # å¦‚æœä½ æ–‡æ¡£éœ€è¦ Git å­æ¨¡å—ï¼Œå–æ¶ˆæ³¨é‡Šä¸‹ä¸€è¡Œ
          # submodules: true

      - name: å®‰è£… pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

     

      - name: æ„å»º project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Deploy to viptv.work
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./packages/viptv-docs/dist
          publish_branch: main
          cname: viptv.work

      - name: Deploy to hefung/docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: hefung/docs
          branch: main
          folder: ./packages/viptv-docs/dist
          token: ${{ secrets.PUBLISH_DOCS }}
          single-commit: true

      - name: Deploy to iptv
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: iptv-js/iptv
          publish_dir: ./packages/iptv-source/dist
          publish_branch: main   

      - name: Commit project ğŸ±â€ğŸ
        run: | 
          git config --local user.email "28900094+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update viptv dev project"

      - name: Push changes ğŸš€
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_DOCS }}
          branch: main     