name: Build And Deploy Docs
on:
  push:
    branches: [main]
  workflow_dispatch:  
  schedule:
    - cron: "00 16 * * *"  
env:
  TZ: Asia/Shanghai
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: ÂÆâË£Ö pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: ËÆæÁΩÆ Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: ÊûÑÂª∫ project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT  

      - name: Deploy to viptv.work
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./packages/viptv-docs/dist
          publish_branch: main
          cname: www.viptv.work

      - name: Deploy to hefung/docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: hefung/docs
          branch: main
          folder: ./packages/viptv-docs/dist
          token: ${{ secrets.PUBLISH_DOCS }}
          single-commit: true

      - name: Deploy to iptv
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: iptv-js/iptv
          publish_dir: ./packages/iptv-source/dist
          publish_branch: main   

      - name: Commit project üê±‚Äçüèç
        if: steps.verify_diff.outputs.changed == 'true'
        run: | 
          git config --local user.email "28900094+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update viptv dev project"

      - name: Push changes üöÄ
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_DOCS }}
          branch: main     
